stages:
  - npm
  - test
  - build

npm-job:
  stage: npm
  script:
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - dist/
      - package.json

unit-test-job:
  stage: test    # It only starts when the job in the build stage completes successfully.
  dependencies:
    - npm-job
  script:
    - npm test

build-job:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    dependencies:
        - npm-job
        - unit-test-job
    script:
        - docker build -t robbyawaldi/example-ci-cd:latest
        - docker push robbyawaldi/example-ci-cd:latest
    only:
        - main
