GET http://localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/users
Content-Type: application/json

###
GET http://localhost:8080/users?filter-city=jakarta
Content-Type: application/json

###
GET http://localhost:8080/users/cities
Content-Type: application/json